### ISSUE TITLE
Server console stating that biome names are invalid

### ISSUE THREAD

**Issue by rakostep** [Darsenia/Traveler-s-Dream#7]
Hi Darsenia and staff, I'd like to notify you about the issue when I was setting up your custom biomes for Traveler's dream. The issue is mainly on server saying that the biome names are invalid (I assume it's OTG also) and tested a couple of times to check if the biome does render in the world. Apparently I see none. Another issue is when I try to apply a biome from a different mod and received a crash report saying:  

```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2021-01-10 06:46:54 EST
Description: Exception in server tick loop

java.lang.RuntimeException: Could not find biome with name 'Komodo Island' from biome group Classic
    at com.pg85.otg.configuration.biome.BiomeGroup.processBiomeData(BiomeGroup.java:104)
    at com.pg85.otg.configuration.biome.BiomeGroupManager.processBiomeData(BiomeGroupManager.java:176)
    at com.pg85.otg.network.ServerConfigProvider.loadSettings(ServerConfigProvider.java:148)
    at com.pg85.otg.network.ServerConfigProvider.<init>(ServerConfigProvider.java:83)
    at com.pg85.otg.forge.world.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:360)
    at com.pg85.otg.forge.world.OTGWorldType.getBiomeProvider(OTGWorldType.java:158)
    at net.minecraft.world.WorldProvider.init(WorldProvider.java:58)
    at net.minecraft.world.WorldProvider.setWorld(WorldProvider.java:40)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:116)
    at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:298)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
```

Do note that I followed the way you set up the Vampirism biome that you include in your mod profile.

Thanks for the time reading this.

Cheers

**Comment by Darsenia** [comment]
Hi! Can you please attach your custom biome .bc file and worldconfig.ini? With a link, or just post them here, in separate messages.
Does this issue happen only on server? If so, do you have the same preset files(with your custom biome) both on client and server?And did you create a new world for server directly by the server or imported world made on client?
